name: Create or Update Jira Issue
on:
  issues:
    types:
      - opened
jobs:
  manage-issue:
    name: Manage Jira Issue
    runs-on: ubuntu-latest
    steps:
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Parse GitHub Issue Body
        id: parse-body
        run: |
          echo "parentKey=$(echo '${{ github.event.issue.body }}' | grep -oP '(?<=parentKey: )\S+')" >> $GITHUB_ENV
          echo "childKey=$(echo '${{ github.event.issue.body }}' | grep -oP '(?<=childKey: )\S+')" >> $GITHUB_ENV
          echo "branch=$(echo '${{ github.event.issue.body }}' | grep -oP '(?<=branch: )\S+')" >> $GITHUB_ENV
          echo "description=$(echo '${{ github.event.issue.body }}' | grep -oP '(?<=description: ).*')" >> $GITHUB_ENV

      - name: Check if Child Task Exists
        id: check-task
        if: ${{ env.childKey != '' }}
        uses: atlassian/gajira-get@v3
        with:
          issue: ${{ env.childKey }}

      - name: Update Child Task to In Progress
        if: ${{ steps.check-task.outputs.issue != '' }}
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.childKey }}
          transition: "In Progress"

      - name: Convert Markdown to Jira Syntax
        if: ${{ steps.check-task.outputs.issue == '' }}
        uses: peter-evans/jira2md@v1
        id: md2jira
        with:
          input-text: |
            ### Github Issue Link
            - ${{ github.event.issue.html_url }}

            ${{ env.description }}
          mode: md2jira

      - name: Create New Child Task
        if: ${{ steps.check-task.outputs.issue == '' }}
        id: create-task
        uses: atlassian/gajira-create@v3
        with:
          project: HW
          issuetype: Task
          summary: '${{ github.event.issue.title }}'
          description: '${{ steps.md2jira.outputs.output-text }}'
          fields: |
            {
              "parent": {
                "key": "${{ env.parentKey }}"
              }
            }

      - name: Create Branch for Task
        run: |
          git fetch origin
          git checkout -b ${{ env.branch }}
          git push origin ${{ env.branch }}

      - name: Log Issue Update or Creation
        run: |
          if [[ "${{ steps.check-task.outputs.issue }}" != "" ]]; then
            echo "Updated existing child task: ${{ env.childKey }} to In Progress."
          else
            echo "Created new child task under parent: ${{ env.parentKey }} with task key: ${{ steps.create-task.outputs.issue }}."
          fi

      - name: Add comment with Jira Task link
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ steps.check-task.outputs.issue != '' && 'Updated existing child task to In Progress: [${{ env.childKey }}](${ secrets.JIRA_BASE_URL }}/browse/${{ env.childKey }})' || 'New child task created under parent task: [${{ steps.create-task.outputs.issue }}](${ secrets.JIRA_BASE_URL }}/browse/${{ steps.create-task.outputs.issue }})' }}
